<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hwparam_document [
<!ELEMENT hwparam_document (hwparam_setting, hwparam_info+)>
<!ELEMENT hwparam_setting ANY>
<!ATTLIST hwparam_setting
    enable CDATA #REQUIRED
    DVServer CDATA #REQUIRED
    DQServer CDATA #REQUIRED
    CFServer CDATA #REQUIRED
    condition CDATA #IMPLIED
    LogBackup CDATA #IMPLIED
    analyzer CDATA #IMPLIED>
<!ELEMENT hwparam_info ANY>
<!ATTLIST hwparam_info
      compID CDATA #REQUIRED
      compVer CDATA #REQUIRED
      compManufacture CDATA #REQUIRED
      hitType CDATA #REQUIRED
      feature CDATA #REQUIRED
      order_compID CDATA #REQUIRED
      order_feature CDATA #REQUIRED
      uevent_path CDATA #IMPLIED>
<!ELEMENT condition_info ANY>
<!ATTLIST condition_info
      path CDATA #REQUIRED
      value CDATA #REQUIRED>
<!ELEMENT sysfs_node (key_info*)>
<!ATTLIST sysfs_node
      type CDATA #REQUIRED
      key CDATA #REQUIRED
      value CDATA #REQUIRED
      clear CDATA #REQUIRED>
<!ELEMENT dev_sysfs_node (key_info*)>
<!ATTLIST dev_sysfs_node
      type CDATA #REQUIRED
      key CDATA #REQUIRED
      value CDATA #REQUIRED
      clear CDATA #REQUIRED>
<!ELEMENT enc_sysfs_node (key_info*)>
<!ATTLIST enc_sysfs_node
      type CDATA #REQUIRED
      key CDATA #REQUIRED
      value CDATA #REQUIRED
      clear CDATA #REQUIRED>
<!ELEMENT data_info (key_info*)>
<!ATTLIST data_info
      interface CDATA #REQUIRED
      type1 CDATA #REQUIRED
      type2 CDATA #REQUIRED
      type3 CDATA #REQUIRED>
<!ELEMENT key_info EMPTY>
<!ATTLIST key_info
      keyname CDATA #REQUIRED
      min CDATA #REQUIRED
      max CDATA #REQUIRED
      desc1 CDATA #REQUIRED
      desc2 CDATA #REQUIRED
      desc3 CDATA #REQUIRED
      desc4 CDATA #REQUIRED
      type1 CDATA #REQUIRED
      type2 CDATA #REQUIRED>
]>

<hwparam_document>

    <hwparam_setting enable="true" DVServer="true" DQServer="true" CFServer="false" />

    <!-- Device : AP -->
    <hwparam_info compID="AP" feature="SYSC" hitType="sm" compVer="0.0" compManufacture="" order_compID="1" order_feature="1" >
        <sysfs_node type="S" key="AP" value="/sys/devices/system/chip-id/ap_id" clear="0" >
            <key_info keyname="AP" min="" max="" desc1="Application Processer" desc2="" desc3="" desc4="" type1="1" type2="10" />
        </sysfs_node>
        <sysfs_node type="S" key="PCB" value="/efs/FactoryApp/control_no" clear="0" >
            <key_info keyname="PCB" min="" max="" desc1="PCB Info." desc2="" desc3="" desc4="" type1="1" type2="10" />
        </sysfs_node>
        <sysfs_node type="S" key="SMD" value="/efs/FactoryApp/HwPartSMDDate" clear="0" >
            <key_info keyname="SMD" min="" max="" desc1="SMD Date" desc2="" desc3="" desc4="" type1="1" type2="10" />
        </sysfs_node>
        <sysfs_node type="M" key="AP_INFO" value="/sys/class/sec/sec_hw_param/ap_info" clear="0" >
            <key_info keyname="HW_REV" min="" max="" desc1="HW revision" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="CHIPID_FAIL" min="" max="" desc1="Check ID read fail" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="LPI_TIMEOUT" min="" max="" desc1="LPI time out" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="CACHE_ERR" min="" max="" desc1="Cache error" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="CODE_DIFF" min="" max="" desc1="Code Diff." desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="ASV_LIT" min="0" max="15" desc1="ASV Group Little Core" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="ASV_BIG" min="0" max="15" desc1="ASV Group Big Core" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="ASV_MIF" min="0" max="15" desc1="ASV group MIF" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="IDS_BIG" min="0" max="15" desc1="IDS Big Core" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="LOT_ID" min="" max="" desc1="LOT ID" desc2="" desc3="" desc4="" type1="1" type2="99" />
        </sysfs_node>
        <sysfs_node type="M" key="AP_INFO" value="/data/system/users/service/data/RC.p" clear="0" >
            <key_info keyname="KP" min="" max="" desc1="Kernel panic" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="DP" min="" max="" desc1="Watchdog reset" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="PP" min="" max="" desc1="Power reset" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="PF_EX" min="" max="" desc1="System server crash" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="PF_NT" min="" max="" desc1="System server native crash" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="PF_SF" min="" max="" desc1="Surfaceflinger native crash" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="PF_WD" min="" max="" desc1="System server watchdog" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="MP" min="" max="" desc1="Manual reset" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="SP" min="" max="" desc1="SMPL" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="WP" min="" max="" desc1="WTSR" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="RP" min="" max="" desc1="User reset" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="BP" min="" max="" desc1="Bootloader reset" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="NP" min="" max="" desc1="Power on" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="TP" min="" max="" desc1="Thermal reset" desc2="" desc3="" desc4="" type1="1" type2="99" />
        </sysfs_node>
    </hwparam_info>

    <hwparam_info compID="AP" feature="DDRV" hitType="sm" compVer="0.0" compManufacture="" order_compID="1" order_feature="2" >
        <sysfs_node type="M" key="DDR_INFO" value="/sys/class/sec/sec_hw_param/ddr_info" clear="0" />
    </hwparam_info>

    <hwparam_info compID="AP" feature="DMVL" hitType="sm" compVer="0.0" compManufacture="" order_compID="1" order_feature ="3" >
	    <sysfs_node type="M" key="" value="/sys/kernel/alta_bigdata/dmv_info" clear="0" />
    </hwparam_info>

    <!-- Device : Memory -->
    <hwparam_info compID="UFS" feature="EUFS" hitType="sm" compVer="0.0" compManufacture="" order_compID="2" order_feature="1" >
      <condition_info path="/sys/class/scsi_host/host0/lt" value="" >
        <sysfs_node type="S" key="PNM" value="/sys/block/sda/device/model" clear="0" >
            <key_info keyname="PNM" min="KLUCG4J1CB-B0B1" max="" desc1="UFS Product Name" desc2="" desc3="" desc4="" type1="1" type2="10" />
        </sysfs_node>
        <sysfs_node type="S" key="REV" value="/sys/block/sda/device/rev" clear="0" >
            <key_info keyname="REV" min="0000" max="9999" desc1="UFS Firmware version" desc2="" desc3="" desc4="" type1="1" type2="10" />
        </sysfs_node>
        <sysfs_node type="S" key="LIFEA" value="/sys/class/scsi_host/host0/lt" clear="0" >
            <key_info keyname="LIFEA" min="1" max="9" desc1="UFS Life Time" desc2="" desc3="" desc4="" type1="1" type2="0" />
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/class/scsi_host/host0/SEC_UFS_err_sum" clear="0">
            <key_info keyname="OPERR" min="" max="" desc1="OPeration ERRor count" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="UICCMD" min="" max="" desc1="UIC CMD error count" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="UICERR" min="" max="" desc1="UIC unipro layer ERRor count" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="FATALERR" min="" max="" desc1="FATAL ERRor count" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="UTPERR" min="" max="" desc1="UTP cmd ERRor count" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="QUERYERR" min="" max="" desc1="QUERY cmd ERRor count" desc2="" desc3="" desc4="" type1="1" type2="0"/>
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/class/scsi_host/host0/SEC_UFS_op_cnt" clear="0">
            <key_info keyname="HWRESET" min="" max="" desc1="HWRESET count" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="LINKFAIL" min="" max="" desc1="Link startup failure count" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="H8ENTERFAIL" min="" max="" desc1="Hibern8 enter failure count" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="H8EXITFAIL" min="" max="" desc1="Hibern8 exit failure count" desc2="" desc3="" desc4="" type1="1" type2="0"/>
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/class/scsi_host/host0/SEC_UFS_query_cnt" clear="0">
            <key_info keyname="NOPERR" min="0" max="20" desc1="NOP ERRor count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="R_DESC" min="0" max="20" desc1="Read Desc error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="W_DESC" min="0" max="20" desc1="Write Desc error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="R_ATTR" min="0" max="20" desc1="Read Attr error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="W_ATTR" min="0" max="20" desc1="Write Attr error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="R_FLAG" min="0" max="20" desc1="Read Flag error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="S_FLAG" min="0" max="20" desc1="Set Flag error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="C_FLAG" min="0" max="20" desc1="Clear Flag error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="T_FLAG" min="0" max="20" desc1="Toggle Flag error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/class/scsi_host/host0/SEC_UFS_uic_cmd_cnt" clear="0">
            <key_info keyname="TESTMODE" min="0" max="20" desc1="DME_TEST_MODE error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="DME_GET" min="0" max="20" desc1="DME_GET error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="DME_SET" min="0" max="20" desc1="DME_SET error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="DME_PGET" min="0" max="20" desc1="DME_PEER_GET error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="DME_PSET" min="0" max="20" desc1="DME_PEER_SET error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="PWRON" min="0" max="20" desc1="DME_POWERON error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="PWROFF" min="0" max="20" desc1="DME_POWEROFF error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="DME_EN" min="0" max="20" desc1="DME_ENABLE error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="DME_RST" min="0" max="20" desc1="DME_RESET error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="EPRST" min="0" max="20" desc1="DME_END_PT_RST error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="LINKSTARTUP" min="0" max="20" desc1="DME_LINK_STARTUP error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="H8ENTER" min="0" max="20" desc1="DME_HIBER_ENTER error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="H8EXIT" min="0" max="20" desc1="DME_HIBER_EXIT error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/class/scsi_host/host0/SEC_UFS_uic_err_cnt" clear="0">
            <key_info keyname="PAERR" min="0" max="20" desc1="PA_GENERIC_ERROR count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="DLPAINITERROR" min="0" max="20" desc1="DL_PA_INIT_ERROR count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="DLNAC" min="0" max="20" desc1="DL_NAC_RECEIVED count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="DLTCREPLAY" min="0" max="20" desc1="DL_TCx_REPLAY count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="NLERR" min="0" max="20" desc1="NL_ERROR count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="TLERR" min="0" max="20" desc1="TL_ERROR count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="DMEERR" min="0" max="20" desc1="DME_ERROR count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/class/scsi_host/host0/SEC_UFS_utp_cnt" clear="0">
            <key_info keyname="UTMRQTASK" min="0" max="20" desc1="UTMR QUERY_TASK error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="UTMRATASK" min="0" max="20" desc1="UTMR ABORT_TASK error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="UTRR" min="0" max="20" desc1="READ error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="UTRW" min="0" max="20" desc1="WRITE error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="UTRSYNCCACHE" min="0" max="20" desc1="SYNC_CACHE error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="UTRUNMAP" min="0" max="20" desc1="UNMAP error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="UTRETC" min="0" max="20" desc1="ETC error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/class/scsi_host/host0/SEC_UFS_fatal_cnt" clear="0">
            <key_info keyname="DFE" min="0" max="20" desc1="Device Fatal Error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="CFE" min="0" max="20" desc1="Controller Fatal Error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="SBFE" min="0" max="20" desc1="System Bus Fatal Error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="CEFE" min="0" max="20" desc1="Crypto Engine Fatal Error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
            <key_info keyname="LLE" min="0" max="20" desc1="Link Lost Error count" desc2="" desc3="" desc4="" type1="0" type2="0"/>
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/block/sda/diskios" clear="1" >
            <key_info keyname="Hours" min="" max="" desc1="Elapsed Hours" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="ReadC" min="" max="" desc1="Read Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="ReadKB" min="" max="" desc1="Read KBs" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="WriteC" min="" max="" desc1="Write Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="WriteKB" min="" max="" desc1="Write KBs" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="DiscardC" min="" max="" desc1="Discard Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="DiscardKB" min="" max="" desc1="Discard KBs" desc2="" desc3="" desc4="" type1="1" type2="0" />
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/class/scsi_host/host0/sense_err_count" clear="0" >
            <key_info keyname="MEDIUM" min="0" max="20" desc1="Medium Error count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="HWERR" min="0" max="20" desc1="HW Error count" desc2="" desc3="" desc4="" type1="1" type2="0" />
        </sysfs_node>
        <sysfs_node type="S" key="UFSLC" value="/sys/class/scsi_host/host0/lc" clear="0" >
            <key_info keyname="UFSLC" min="" max="" desc1="UFS LVD count" desc2="" desc3="" desc4="" type1="1" type2="0" />
        </sysfs_node>
      </condition_info>
    </hwparam_info>
    <hwparam_info compID="UFS" feature="SUFS" hitType="sm" compVer="0.0" compManufacture="" order_compID="2" order_feature="2" >
      <condition_info path="/sys/class/scsi_host/host0/sense_err_logging" value="" >
        <sysfs_node type="M" key="" value="/sys/class/scsi_host/host0/sense_err_logging" clear="0" >
            <key_info keyname="LBA0" min="" max="" desc1="1st LBA info with MEDIUM_ERROR" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="LBA1" min="" max="" desc1="2nd LBA info with MEDIUM_ERROR" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="LBA2" min="" max="" desc1="3rd LBA info with MEDIUM_ERROR" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="LBA3" min="" max="" desc1="4th LBA info with MEDIUM_ERROR" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="LBA4" min="" max="" desc1="5th LBA info with MEDIUM_ERROR" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="LBA5" min="" max="" desc1="6th LBA info with MEDIUM_ERROR" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="LBA6" min="" max="" desc1="7th LBA info with MEDIUM_ERROR" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="LBA7" min="" max="" desc1="8th LBA info with MEDIUM_ERROR" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="LBA8" min="" max="" desc1="9th LBA info with MEDIUM_ERROR" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="LBA9" min="" max="" desc1="10th LBA info with MEDIUM_ERROR" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="REGIONMAP" min="" max="" desc1="MEDIUM_ERROR region map step 200MB" desc2="" desc3="" desc4="" type1="1" type2="99" />
        </sysfs_node>
      </condition_info>
    </hwparam_info>
    <hwparam_info compID="UFS" feature="TUFS" hitType="sm" compVer="0.0" compManufacture="" order_compID="2" order_feature="3" >
      <condition_info path="/sys/class/scsi_host/host0/SEC_UFS_TW_info" value="" >
        <sysfs_node type="M" key="" value="/sys/class/scsi_host/host0/SEC_UFS_TW_info" clear="0" >
            <key_info keyname="TWCTRLCNT" min="" max="" desc1="TW CTRL CouNT" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="TWCTRLERRCNT" min="" max="" desc1="TW CTRL ERRor CouNT" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="TWDAILYMB" min="" max="" desc1="TW DAILY write size MB" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="TWTOTALMB" min="" max="" desc1="TW TOTAL write size MB" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="H8CNT" min="" max="" desc1="Hibern8 enter CouNT" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="H8MS" min="" max="" desc1="Hibern8 entered time MS" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="H8CNT100MS" min="" max="" desc1="Hibern8 enter CouNT 100ms or more" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="H8MS100MS" min="" max="" desc1="Hibern8 entered time MS 100ms or more" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="H8MAXMS" min="" max="" desc1="Hibern8 entered MAX time MS" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="TWhours" min="" max="" desc1="TW info Elapsed Hours" desc2="" desc3="" desc4="" type1="1" type2="0" />
        </sysfs_node>
      </condition_info>
    </hwparam_info>

    <!-- Device : eMMC / Storage -->
    <hwparam_info compID="MMC" feature="EMMC" hitType="sm" compVer="0.0" compManufacture="" order_compID="2" order_feature="1" >
      <condition_info path="/sys/class/sec/mmc/mmc_data" value="" >
        <sysfs_node type="M" key="" value="/sys/class/sec/mmc/mmc_data" clear="0" >
            <key_info keyname="GE" min="" max="" desc1="General Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="CC" min="" max="" desc1="Card Controller Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="ECC" min="0" max="100" desc1="Card ECC Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="WP" min="" max="" desc1="Write Protection Violation" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="OOR" min="" max="" desc1="Oot Of Range Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="CRC" min="" max="" desc1="CRC Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="TMO" min="0" max="200" desc1="Timeout Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="HALT" min="" max="" desc1="Halt unhalt Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="CQED" min="" max="" desc1="CQ enable disable Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="RPMB" min="" max="" desc1="RPMB switch Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/class/sec/mmc/mmc_summary" clear="0" >
            <key_info keyname="MANID" min="" max="" desc1="Manufacture ID" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="PNM" min="" max="" desc1="Product Name" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="REV" min="" max="" desc1="FW rev" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="CQ" min="" max="" desc1="Command Queue usage" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="SIZE" min="" max="" desc1="Storage capacity" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="SPEEDMODE" min="" max="" desc1="Current Bus Speed Mode" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="LIFE" min="" max="" desc1="Lifetime" desc2="" desc3="" desc4="" type1="1" type2="0"/>
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/block/mmcblk0/diskios" clear="1" >
            <key_info keyname="Hours" min="" max="" desc1="Elapsed Hours" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="ReadC" min="" max="" desc1="Read Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="ReadKB" min="" max="" desc1="Read KBs" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="WriteC" min="" max="" desc1="Write Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="WriteKB" min="" max="" desc1="Write KBs" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="DiscardC" min="" max="" desc1="Discard Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="DiscardKB" min="" max="" desc1="Discard KBs" desc2="" desc3="" desc4="" type1="1" type2="0" />
        </sysfs_node>
      </condition_info>
    </hwparam_info>

    <!-- Device : SDcard / Storage -->
    <hwparam_info compID="SDcard" feature="SDMC" hitType="sm" compVer="0.0" compManufacture="" order_compID="3" order_feature="1" >
      <condition_info path="/sys/class/sec/sddata/sd_data" value="" >
        <sysfs_node type="S" key="CDCNT" value="/sys/class/sec/sdcard/cd_cnt" clear="0" >
            <key_info keyname="CDCNT" min="0" max="500" desc1="Card Detection count" desc2="" desc3="" desc4="" type1="1" type2="0" />
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/class/sec/sddata/sd_data" clear="0" >
            <key_info keyname="GE" min="" max="" desc1="General Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="CC" min="" max="" desc1="Card Controller Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="ECC" min="0" max="100" desc1="Card ECC Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="WP" min="" max="" desc1="Write Protection Violation" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="OOR" min="" max="" desc1="Oot Of Range Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="CRC" min="" max="" desc1="CRC Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="TMO" min="0" max="200" desc1="Timeout Error" desc2="" desc3="" desc4="" type1="1" type2="0"/>
        </sysfs_node>
        <sysfs_node type="M" key="" value="/sys/class/sec/sdcard/sdcard_summary" clear="0" >
            <key_info keyname="MANID" min="" max="" desc1="Manufacture ID" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="SERIAL" min="" max="" desc1="Partialy SD Card Serial" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="SIZE" min="" max="" desc1="SD Card Size" desc2="" desc3="" desc4="" type1="1" type2="0"/>
            <key_info keyname="SPEEDMODE" min="" max="" desc1="Current SD Card run Speed Mode" desc2="" desc3="" desc4="" type1="1" type2="0"/>
	    <key_info keyname="NOTI" min="" max="" desc1="SD Card IO Error Notification Count" desc2="" desc3="" desc4="" type1="1" type2="0"/>
        </sysfs_node>
      </condition_info>
    </hwparam_info>

    <!-- Device : Display -->
    <hwparam_info compID="Display" feature="DPUI" hitType="sm" compVer="0.0" compManufacture="" order_compID="4" order_feature="1" >
        <sysfs_node type="M" key="" value="/sys/class/lcd/panel/dpui" clear="1" >
            <key_info keyname="DISP_MODEL" min="" max="" desc1="Display Vendor and Model Name" desc2="" desc3="" desc4="" type1="1" type2="10" />
            <key_info keyname="LCDM_ID1" min="0" max="255" desc1="LCD ID1: Fab, window color info." desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="LCDM_ID2" min="0" max="255" desc1="LCD ID2: Touch IC, DCDC IC, EL material info." desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="LCDM_ID3" min="0" max="255" desc1="LCD ID3: D-IC, Op code info." desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="MAID_DATE" min="" max="" desc1="Manufacture date and time" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="WCRD_X" min="" max="" desc1="lcd white rgb x-coordinate" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="WCRD_Y" min="" max="" desc1="lcd white rgb y-coordinate" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="WOFS_R" min="" max="" desc1="lcd white red offset from user" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="WOFS_G" min="" max="" desc1="lcd white green offset from user" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="WOFS_B" min="" max="" desc1="lcd white blue offset from user" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="CHIPID" min="" max="" desc1="Display Driver-IC CHIP ID" desc2="" desc3="" desc4="" type1="1" type2="99" />
            <key_info keyname="PNDSIE" min="" max="" desc1="Panel DSI Error Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="PNELVDE" min="" max="" desc1="Panel ELVDD Error Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="PNVLI1E" min="" max="" desc1="Panel VLIN1 Error Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="PNVLO3E" min="" max="" desc1="Panel VLOUT3 Error Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="PNESDE" min="" max="" desc1="Panel ESD Error Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
            <key_info keyname="PNSDRE" min="" max="" desc1="Panel OTP Loading Error Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
        </sysfs_node>
        <dev_sysfs_node type="M" key="" value="/sys/class/lcd/panel/dpui_dbg" clear="0" />
    </hwparam_info>

    <hwparam_info compID="Display" feature="DPCL" hitType="sm" compVer="0.0" compManufacture="" order_compID="4" order_feature="2" >
        <sysfs_node type="M" key="" value="/sys/class/lcd/panel/dpci" clear="1" >
            <key_info keyname="EXY_SWRCV" min="" max="" desc1="Display Controller S/W Recovery Count" desc2="" desc3="" desc4="" type1="1" type2="0" />
        </sysfs_node>
        <dev_sysfs_node type="M" key="" value="/sys/class/lcd/panel/dpci_dbg" clear="0" />
    </hwparam_info>

    <hwparam_info compID="Display" feature="DAHW" hitType="sm" compVer="0.0" compManufacture="sec" order_compID="4" order_feature="3">
        <data_info interface="A" type1="" type2="" type3="" >